<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> meeting deletion' => '<strong>Bekreft</strong> sletting av møte',
    '<strong>Create</strong> new meeting' => '<strong>Opprett</strong> nytt møte',
    '<strong>Edit</strong> meeting' => '<strong>Redigér</strong> møte',
    'Add external participants (free text)' => 'Legg til eksterne deltagere (fri tekst)',
    'Add participants' => 'Legg til deltagere',
    'Do you really want to delete this meeting?' => 'Vil du virkelig slette dette møtet?',
    'External participants' => 'Eksterne deltagere',
    'Location' => 'Sted',
    'Room' => 'rom',
    'Title of your meeting' => 'Tittel på møtet',
    'hh:mm' => 'tt:mm',
];
