<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> entry deletion' => '<strong>Bekreft</strong> sletting av agendapunkt',
    '<strong>Create</strong> new entry' => '<strong>Opprett</strong> nytt punkt på agendaen',
    '<strong>Edit</strong> entry' => '<strong>Rediger</strong> agendapunkt',
    'Add external moderators (free text)' => 'Legg til eksterne moderatorer (fri tekst)',
    'Add moderator' => 'Legg til moderator',
    'Do you really want to delete this entry?' => 'Vil du virkelig slette dette punktet?',
    'External moderators' => 'Eksterne moderatorer',
    'Subject' => 'Tittel',
    'Title of this entry' => 'Tittel på agendapunkt',
];
