<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Share</strong> meeting' => '<strong>Del</strong> møte',
    'Add to your calendar and invite participants' => 'Legg til i din kalender og inviter deltagere',
    'Add to your personal calendar' => 'Legg til i din personlige kalender',
    'Export ICS' => 'Eksporter ICS',
    'Send notifications to all participants' => 'Send varsel til alle deltagere',
    'Send now' => 'Send nå',
    'Sends internal notifications to all participants of the meeting.' => 'Sender internt varsel til alle deltagere av møtet.',
    'This will create an ICS file, which adds this meeting only to your private calendar.' => 'Dette vil opprette en ICS-fil som kan brukes for å legge til møtet i din personlige kalender.',
    'This will create an ICS file, which adds this meeting to your personal calendar, invite all other participants by email and waits for their response.' => 'Dette vil opprette en ICS-fil som kan brukes for å legge til møtet i din personlige kalender, invitere brukere og avvente deres svar.',
];
