<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> entry deletion' => '<strong>Confirmer</strong> la suppression de l\'activité',
    '<strong>Create</strong> new entry' => '<strong>Créer</strong> une nouvelle activité',
    '<strong>Edit</strong> entry' => '<strong>Modifier</strong> l\'activité',
    'Add external moderators (free text)' => 'Ajouter des modérateurs externes (texte libre)',
    'Add moderator' => 'Ajouter modérateur',
    'Do you really want to delete this entry?' => 'Voulez-vous vraiment supprimer cette activité ?',
    'External moderators' => 'Modérateurs externes',
    'Subject' => 'Objet',
    'Title of this entry' => 'Titre de cette activité',
];
