<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> meeting deletion' => '<strong>Confirmer</strong> la suppression de la réunion',
    '<strong>Create</strong> new meeting' => '<strong>Créer</strong> une nouvelle réunion',
    '<strong>Edit</strong> meeting' => '<strong>Modifier</strong> la réunion',
    'Add external participants (free text)' => 'Ajouter des participants externes (texte libre)',
    'Add participants' => 'Ajouter des participants',
    'Do you really want to delete this meeting?' => 'Voulez-vous vraiment supprimer cette réunion ?',
    'External participants' => 'Participants externes',
    'Location' => 'Lieu',
    'Room' => 'Salle',
    'Title of your meeting' => 'Titre de votre réunion',
    'hh:mm' => 'hh:mm',
];
