<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> entry deletion' => '<strong>Bevestig</strong> het wissen van het item',
    '<strong>Create</strong> new entry' => '<strong>Maak</strong> een nieuw item',
    '<strong>Edit</strong> entry' => '<strong>Bewerk</strong> het item',
    'Add external moderators (free text)' => 'Voeg externe moderatoren toe (vrije tekst)',
    'Add moderator' => 'Voeg moderator toe',
    'Do you really want to delete this entry?' => 'Wilt u dit item echt verwijderen?',
    'External moderators' => 'Externe moderator',
    'Subject' => 'Onderwerp',
    'Title of this entry' => 'Omschrijving van dit item',
];
