<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> entry deletion' => '<strong>Potrdit</strong> smazání záznamu',
    '<strong>Create</strong> new entry' => '<strong>Vytvořit</strong> nový záznam',
    '<strong>Edit</strong> entry' => '<strong>Upravit</strong> záznam',
    'Add external moderators (free text)' => 'Přidat externí moderátory (libovolný text)',
    'Add moderator' => 'Přidat moderátora',
    'Do you really want to delete this entry?' => 'Opravdu chcete smazat tento záznam?',
    'External moderators' => 'Externí moderátoři',
    'Subject' => 'Předmět',
    'Title of this entry' => 'Název záznamu',
];
