<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Share</strong> meeting' => '<strong>Sdílet</strong> schůzku',
    'Add to your calendar and invite participants' => 'Přidat do kalendáře a pozvat účastníky',
    'Add to your personal calendar' => 'Přidat do Vašeho osobního kalendáře',
    'Export ICS' => 'Exporotvat ICS',
    'Send notifications to all participants' => 'Zaslat upozornění všem účastníkům',
    'Send now' => 'Odeslat nyní',
    'Sends internal notifications to all participants of the meeting.' => 'Poslat interní upozornění všem účastníkům schůzky',
    'This will create an ICS file, which adds this meeting only to your private calendar.' => 'Vytvořit soubor .ICS, pro přidání do Vašeho osobního kalendáře.',
    'This will create an ICS file, which adds this meeting to your personal calendar, invite all other participants by email and waits for their response.' => 'Tímto vytvoříte soubor ICS, který tuto schůzku přidá do osobního kalendáře, pozvěte ostatní účastníky e-mailem a počkejte na jejich odpověď.',
];
