<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Can manage meeting content' => '',
    'Begin' => 'Bắt đầu',
    'Date' => 'Ngày',
    'Duplicate agenda entries' => 'Tạo bản sao chương trình họp',
    'End' => 'Kết thúc',
    'Location' => 'Địa điểm',
    'Manage Meetings' => 'Quản lý Họp',
    'Participants' => 'Thành viên tham gia',
    'Participants (External)' => 'Thành viên tham gia (bên ngoài)',
    'Room' => 'Phòng',
    'Title' => 'Tiêu đề',
];
