<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> meeting deletion' => '<strong>Potwierdź</strong> usunięcie spotkania',
    '<strong>Create</strong> new meeting' => '<strong>Utwórz</strong> nowe spotkanie',
    '<strong>Edit</strong> meeting' => '<strong>Edytuj</strong> spotkanie',
    'Add external participants (free text)' => 'Dodaj zewnętrznych uczestników (otwarty tekst)',
    'Add participants' => 'Dodaj uczestników',
    'Do you really want to delete this meeting?' => 'Na pewno usunąć to spotkanie?',
    'External participants' => 'Zewnętrzni uczestnicy',
    'Location' => 'Miejsce',
    'Room' => 'Pokój',
    'Title of your meeting' => 'Tytuł twojego spotkania',
    'hh:mm' => 'gg:mm',
];
