<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Next</strong> meetings' => '',
    '<strong>Past</strong> meetings' => '',
    'Add a protocol' => '',
    'Add a task' => '',
    'Create your first agenda entry by clicking the following button.' => '',
    'External participants' => '',
    'Moderators' => '',
    'New agenda entry' => '',
    'New meeting' => '',
    'Participants' => '',
    'Print agenda' => '',
    'Protocol' => '',
    'Share meeting' => '',
    'Start now, by creating a new meeting!' => '',
    'Tasks' => '',
    'Today' => '',
    'Tomorrow' => '',
    'Unfortunately, there was no entry made until now.' => '',
];
