<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Share</strong> meeting' => '<strong>Compartilhar</strong> reunião',
    'Add to your calendar and invite participants' => 'Adicione ao seu calendário e convidar os participantes',
    'Add to your personal calendar' => 'Adicionar ao seu calendário pessoal',
    'Export ICS' => 'Exportar ICS',
    'Send notifications to all participants' => 'Enviar notificações a todos os participantes',
    'Send now' => 'Enviar agora',
    'Sends internal notifications to all participants of the meeting.' => 'Envia notificações internas a todos os participantes da reunião.',
    'This will create an ICS file, which adds this meeting only to your private calendar.' => 'Isso criará um arquivo ICS, que adicionará esta reunião somente ao seu calendário particular.',
    'This will create an ICS file, which adds this meeting to your personal calendar, invite all other participants by email and waits for their response.' => 'Isto criará um arquivo ICS, que adicionará esta reunião ao seu calendário pessoal, convidará todos os outros participantes por e-mail e aguardará suas respostas.',
];
