<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> meeting deletion' => '<strong>Confirmar</strong> eliminação de reunião',
    '<strong>Create</strong> new meeting' => '<strong>Criar</strong> nova reunião',
    '<strong>Edit</strong> meeting' => '<strong>Editar</strong> reunião',
    'Add external participants (free text)' => 'Adicionar participantes externos (texto livre)',
    'Add participants' => 'Adicionar participantes',
    'Do you really want to delete this meeting?' => 'Deseja mesmo excluir esta reunião?',
    'External participants' => 'Participantes externos',
    'Location' => 'Localização',
    'Room' => 'Sala',
    'Title of your meeting' => 'Título da sua reunião',
    'hh:mm' => 'hh:mm',
];
